site_name: Hemerson Vianna
theme_url: http://hemersonvianna.com
home_title: Início
home_description: Bem-vindo!! Me chamo Hemerson Vianna, e venho acumulando experiência de vida desde 1986. Gosto de compartilhar ideias sobre TI e outros assuntos.

# Header
menu:
  Home: /
  About: /about
  Artigos: /categories
  Contato: /contact
rss: /atom.xml

# Content
excerpt_link: Leia mais

# Sidebar
sidebar: right
widgets:
- category
- recent_posts

disqus_shortname: hemersonvianna

# Miscellaneous
google_analytics: UA-27637132-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
